addons:
  - firefox: "45.0"
sudo: required
language: c
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xvfb
install:
  - sudo -H pip install selenium
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script:
  - bash -ex .travis-opam.sh
  - xvfb-run test/test.py test/test.html
  - xvfb-run test/test.py test/test_native.html
env:
  global:
    - PACKAGE=selenium-test
  matrix:
    - OCAML_VERSION=4.02
